export const APP = {
	apiUrl: import.meta.env.VITE_API_URL || "http://localhost:8080",
	apiKey: import.meta.env.VITE_API_KEY || "66eaedcb-9315-4574-bc19-ae19506a07b0",
	appName: "25Karma",
	appNickname : "+25 Karma!",
	documentTitle: "25Karma",
	hypixelStatusUrl: "https://status.hypixel.net",
	namemcUrl: "https://namemc.com/search?q=",
	organizationUrl: "https://github.com/25karma",
	ownerHypixelForumsUrl: "",
	ownerUsername: "",
	skyblockUrl: "https://sky.shiiyu.moe/stats",
	suggestedPlayers: ["Technoblade", "gamerboy80", "Technoblade"],
	discordUrl: "",
	announcement: {
		enabled: false,
		text: "",
		linkText: "",
		linkUrl: "",
		backgroundColor: "",
		icon: "",
		dismissible: true,
		dismissCooldownDays: -1,
	},
}
